replicaCount: 1

image:
  repository: 830706739344.dkr.ecr.us-west-2.amazonaws.com/finix-apps/accept-a-payment
  tag: latest
  pullPolicy: Always

service:
  name: accept-a-payment
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 250m
    memory: 500Mi

readinessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

livenessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

namespace: frontend-domain
