on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          # - dev
          - prod
      jira_ticket:
        description: 'Release management Jira ticket'
        type: string
        required: true
permissions:
  contents: read
jobs:
  build:
    uses: finix-payments/finix-github-actions/.github/workflows/build-nodejs-project.yaml@main
    with: 
      run_node_tests: false
  deploy:
    needs: 
      - build
    uses: finix-payments/finix-github-actions/.github/workflows/publish-to-finix-cdn.yaml@main
    with: 
      environment: ${{ inputs.environment }}
      s3_path: "accept-a-payment-${{ inputs.environment }}"
